# Easy Level (1–10)
# Q1 Load the dataset and display the first 10 records.

In [100]:
import pandas as pd
df=pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [101]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

# Q2 Display the last 15 customers.

In [102]:
ver=df.tail(15)
ver

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

# Q3 Show 7 random customer records.

In [103]:
ver=df.sample(7)
ver

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6189,6190,15572408,Chambers,714,Germany,Male,39,3,149887.49,2,1,0,63846.36,0
1842,1843,15747222,Bentley,745,Spain,Female,35,8,0.00,2,1,1,116581.10,0
6615,6616,15792934,Carruthers,661,France,Male,26,8,0.00,2,0,0,196875.87,0
8204,8205,15570141,P'eng,724,France,Female,34,3,132352.69,1,1,0,80320.30,0
541,542,15626578,Milne,622,France,Male,26,9,0.00,2,1,1,153237.59,0
2522,2523,15758056,Calabresi,558,France,Male,35,1,0.00,2,0,0,111687.57,0
1933,1934,15815560,Bogle,666,Germany,Male,74,7,105102.50,1,1,1,46172.47,0

In [104]:
# Q4
Print complete dataset information and identify:
• Total columns
• Data type of each column
• Missing values

SyntaxError: invalid character '•' (U+2022) (4243364182.py, line 3)

In [105]:
ver=df.info()
print(ver)
print("data type",df.dtypes)
print("missing values:",df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB
None
data type RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object
missing values: RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

# Q5 Find missing values in every column.

In [106]:
ver=df.isnull().sum()
ver

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

# Q6 Display only numerical columns.

In [107]:
ver=df.select_dtypes(include=["number"]).columns
ver

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

# Q7 Generate the statistical summary of numerical columns.

In [108]:
ver=df.describe()
ver

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

## Q8 Find duplicate rows and print how many exist.

In [109]:
ver=df.duplicated().sum()
ver

np.int64(0)

## Q9 Remove duplicate rows and store the cleaned dataset.

In [110]:
df.drop_duplicates(inplace=True)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Q10 Count how many customers have exited and how many have not exited.

In [111]:
ver=df['Exited'].value_counts()
ver

Exited
0    7963
1    2037
Name: count, dtype: int64

In [112]:
# Medium Level (11–20)
Q11
Rename the following columns:
CustomerId → Customer_ID
CreditScore → Credit_Score
EstimatedSalary → Salary
Exited → Churn

SyntaxError: invalid character '→' (U+2192) (1514500550.py, line 4)

In [113]:
var=df.rename(columns ={"CustomerId":"Customer_ID","CreditScore":"Credit_Score","EstimatedSalary":"Salary","Exited":"Churn"},inplace=True)
df.columns

Index(['RowNumber', 'Customer_ID', 'Surname', 'Credit_Score', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'Salary', 'Churn'],
      dtype='object')

In [114]:
## Q12
Add the prefix
Bank_
to every column name.

SyntaxError: invalid syntax (4249269770.py, line 2)

In [115]:
ver=df.add_prefix('Bank_')
ver

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Q13 Convert the Age column into float datatype.

In [116]:
ver['Bank_Age']=ver['Bank_Age'].astype("float")
ver['Bank_Age']

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Bank_Age, Length: 10000, dtype: float64

In [117]:
ver=df.add_prefix('Bank_')
ver

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Q13 Convert the Age column into float datatype.

In [118]:
ver['Bank_Age']=ver['Bank_Age'].astype("float")
ver['Bank_Age']

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Bank_Age, Length: 10000, dtype: float64

## Q14 Convert the Exited column into string datatype.

In [119]:
ver['Bank_Churn']=ver['Bank_Churn'].astype(str)
ver['Bank_Churn']

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Bank_Churn, Length: 10000, dtype: object

In [120]:
## Q15
Suppose the Balance column has missing values.
Replace them using the mean of the Balance column.

SyntaxError: invalid syntax (2453823901.py, line 2)

In [121]:
mean=ver['Bank_Balance'].mean()
ver['Bank_Balance'].fillna(mean)

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Bank_Balance, Length: 10000, dtype: float64

In [122]:
## Q16
Suppose the Age column has missing values.
Replace them using the median age.

SyntaxError: invalid syntax (3425259125.py, line 2)

In [123]:
median=ver['Bank_Age'].median()
ver['Bank_Age']=ver['Bank_Age'].fillna(median)
print(ver['Bank_Age'])

0       42.0
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Bank_Age, Length: 10000, dtype: float64

In [124]:

print(ver['Bank_Age'].isnull().sum())

0

In [125]:
## Q17
Display only the first five rows after renaming the columns.

SyntaxError: invalid syntax (3466794235.py, line 2)

In [126]:
ver.head(5)

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [127]:
## Q18
Create a new DataFrame by dropping these columns:
RowNumber
CustomerId
Surname
Display the first 10 rows.

SyntaxError: invalid syntax (3995694223.py, line 2)

In [128]:
ver.drop(columns=['Bank_RowNumber', 'Bank_Customer_ID', 'Bank_Surname'])
ver.head(10)

,Bank_RowNumber,Bank_Customer_ID,Bank_Surname,Bank_Credit_Score,Bank_Geography,Bank_Gender,Bank_Age,Bank_Tenure,Bank_Balance,Bank_NumOfProducts,Bank_HasCrCard,Bank_IsActiveMember,Bank_Salary,Bank_Churn
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50.0,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29.0,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44.0,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27.0,2,134603.88,1,1,1,71725.73,0

In [129]:
## Q20
Rename NumOfProducts to Products and HasCrCard to CreditCard.

SyntaxError: invalid syntax (959065988.py, line 2)

In [130]:
ver.rename(columns ={"Bank_NumOfProducts":"Products","Bank_HasCrCard":"CreditCard"},inplace=True)
ver.columns

Index(['Bank_RowNumber', 'Bank_Customer_ID', 'Bank_Surname',
       'Bank_Credit_Score', 'Bank_Geography', 'Bank_Gender', 'Bank_Age',
       'Bank_Tenure', 'Bank_Balance', 'Products', 'CreditCard',
       'Bank_IsActiveMember', 'Bank_Salary', 'Bank_Churn'],
      dtype='object')

In [131]:
## Hard Level (21–30)
Q21 (Real Company Task)
Your manager wants cleaner column names.
Rename every column as follows:
RowNumber → Row_No
CustomerId → Customer_ID
Surname → Last_Name
CreditScore → Credit_Score
Geography → Country
Gender → Sex
EstimatedSalary → Salary
Exited → Target
Display the first five rows.

SyntaxError: invalid character '→' (U+2192) (820249438.py, line 5)

In [132]:

ver.rename(columns={
    "Bank_RowNumber" : "Row_No",
    "Bank_Customer_ID": "Customer_ID",
    "Bank_Surname" : "Last_Name",
    "Bank_Credit_Score" :"Credit_Score",
    "Bank_Geography" : "Country",
    "Bank_Gender" : "Sex",
    "Bank_Salary ":" Salary",
    "Bank_Churn": "Target",
},inplace=True)
ver.columns

Index(['Row_No', 'Customer_ID', 'Last_Name', 'Credit_Score', 'Country', 'Sex',
       'Bank_Age', 'Bank_Tenure', 'Bank_Balance', 'Products', 'CreditCard',
       'Bank_IsActiveMember', 'Bank_Salary', 'Target'],
      dtype='object')

# Q22
# Create a new DataFrame that contains only numeric columns.
# Then generate its statistical summary.

In [133]:
numeric_ver = ver.select_dtypes(include='number')
numeric_ver.describe()

,Row_No,Customer_ID,Credit_Score,Bank_Age,Bank_Tenure,Bank_Balance,Products,CreditCard,Bank_IsActiveMember,Bank_Salary
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000

In [134]:
# Q23
Your company received duplicate customer records.
Tasks:
• Count duplicates.
• Remove duplicates.
• Display dataset information after cleaning.

SyntaxError: invalid character '•' (U+2022) (3476713788.py, line 4)

In [135]:
ver.duplicated().sum()
ver.drop_duplicates()

,Row_No,Customer_ID,Last_Name,Credit_Score,Country,Sex,Bank_Age,Bank_Tenure,Bank_Balance,Products,CreditCard,Bank_IsActiveMember,Bank_Salary,Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [136]:
ver.duplicated().sum()

np.int64(0)

In [137]:
# Q24
Management wants every column name to begin with
Customer_

Sumit Sir Notes
Apply this transformation using the appropriate method.

SyntaxError: invalid syntax (334272077.py, line 2)

In [138]:
ver=ver.add_prefix("Customer_")
ver
ver.head(5)

,Customer_Row_No,Customer_Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Sex,Customer_Bank_Age,Customer_Bank_Tenure,Customer_Bank_Balance,Customer_Products,Customer_CreditCard,Customer_Bank_IsActiveMember,Customer_Bank_Salary,Customer_Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [139]:
ver.columns = ver.columns.str.replace('Customer_Customer_', 'Customer_', regex=False)

ver.head(5)

,Customer_Row_No,Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Sex,Customer_Bank_Age,Customer_Bank_Tenure,Customer_Bank_Balance,Customer_Products,Customer_CreditCard,Customer_Bank_IsActiveMember,Customer_Bank_Salary,Customer_Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [140]:
## Q25
After renaming the columns, convert
Age
Balance
Salary
to float datatype.
Print dataset information.

SyntaxError: invalid syntax (3359979639.py, line 2)

In [141]:
ver[['Customer_Bank_Age', 'Customer_Bank_Balance', 'Customer_Bank_Salary']] = ver[['Customer_Bank_Age', 'Customer_Bank_Balance', 'Customer_Bank_Salary']].astype(float)

ver[['Customer_Bank_Age', 'Customer_Bank_Balance', 'Customer_Bank_Salary']]

      Customer_Bank_Age  Customer_Bank_Balance  Customer_Bank_Salary
0                  42.0                   0.00             101348.88
1                  41.0               83807.86             112542.58
2                  42.0              159660.80             113931.57
3                  39.0                   0.00              93826.63
4                  43.0              125510.82              79084.10
...                 ...                    ...                   ...
9995               39.0                   0.00              96270.64
9996               35.0               57369.61             101699.77
9997               36.0                   0.00              42085.58
9998               42.0               75075.31              92888.52
9999               28.0              130142.79              38190.78

[10000 rows x 3 columns]

In [142]:
## Q26
Assume CreditScore contains missing values.
Replace them with the median CreditScore.

SyntaxError: invalid syntax (2849461466.py, line 2)

In [143]:
ver['Customer_Credit_Score'].isnull().sum()

np.int64(0)

In [144]:
median=ver['Customer_Credit_Score'].median()
median

652.0

In [ ]:
## Q27
Assume EstimatedSalary contains missing values.
Replace them with the mean salary.
Then print the first eight rows.

In [146]:
ver['Customer_Bank_Salary'].isnull().sum()

np.int64(0)

In [147]:
mean=ver['Customer_Bank_Salary'].mean()
mean

np.float64(100090.239881)

In [148]:
ver['Customer_Bank_Salary'].fillna(mean)

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: Customer_Bank_Salary, Length: 10000, dtype: float64

In [149]:
ver.head(8)

,Customer_Row_No,Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Sex,Customer_Bank_Age,Customer_Bank_Tenure,Customer_Bank_Balance,Customer_Products,Customer_CreditCard,Customer_Bank_IsActiveMember,Customer_Bank_Salary,Customer_Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50.0,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29.0,4,115046.74,4,1,0,119346.88,1

In [ ]:
## Q28 (Data Cleaning Challenge)
Perform all the following:
• Remove duplicate rows.
• Rename Exited to Target.
• Convert Target to string.
• Display dataset information.

In [161]:
ver['Customer_Target']=ver['Customer_Target'].astype("str")
ver['Customer_Target']

0       1.0
1       0.0
2       1.0
3       0.0
4       0.0
       ...
9995    0.0
9996    0.0
9997    1.0
9998    1.0
9999    0.0
Name: Customer_Target, Length: 10000, dtype: object

In [162]:
ver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Customer_Row_No               10000 non-null  int64
 1   Customer_ID                   10000 non-null  int64
 2   Customer_Last_Name            10000 non-null  object
 3   Customer_Credit_Score         10000 non-null  int64
 4   Customer_Country              10000 non-null  object
 5   Customer_Sex                  10000 non-null  object
 6   Customer_Bank_Age             10000 non-null  float64
 7   Customer_Bank_Tenure          10000 non-null  int64
 8   Customer_Bank_Balance         10000 non-null  float64
 9   Customer_Products             10000 non-null  int64
 10  Customer_CreditCard           10000 non-null  int64
 11  Customer_Bank_IsActiveMember  10000 non-null  int64
 12  Customer_Bank_Salary          10000 non-null  float64
 13  Customer_Target               10000 non-null  object
dtypes: float64(3), int64(7), object(4)
memory usage: 1.1+ MB

In [ ]:
## Q29 (Transformation Challenge)
Create a copy of the dataset.

Sumit Sir Notes
Perform these transformations:
• Rename Gender to CustomerGender
• Rename Geography to Country
• Add prefix Bank_
• Remove RowNumber
• Display first 10 rows

In [163]:
ver.head(2)

,Customer_Row_No,Customer_ID,Customer_Last_Name,Customer_Credit_Score,Customer_Country,Customer_Sex,Customer_Bank_Age,Customer_Bank_Tenure,Customer_Bank_Balance,Customer_Products,Customer_CreditCard,Customer_Bank_IsActiveMember,Customer_Bank_Salary,Customer_Target
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1,1,101348.88,1.0
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0.0

In [164]:
ver.to_csv('cleaned_data2.csv', index=False)