# 1. Load the dataset using the appropriate Pandas method and store it in avariable named df.

In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## 2. Display the first 8 rows of the dataset.

In [2]:
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

## 3. Display the last 12 rows of the dataset.

In [3]:
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

# 4. Show 10 random rows from the dataset.

In [4]:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
7144,7145,15577515,Sung,554,Germany,Female,55,0,108477.27,1,0,1,140003.00,1
3131,3132,15614187,Pottinger,648,Germany,Female,39,3,126935.98,2,0,1,57995.74,0
5552,5553,15651315,Dilke,627,France,Male,41,3,0.00,2,1,0,132719.80,0
6111,6112,15803337,Baresi,648,France,Male,23,9,168372.52,1,1,0,134676.72,0
7252,7253,15730673,Dietz,567,Germany,Male,40,7,122265.24,1,1,0,138552.74,0
5953,5954,15696141,Kruglov,516,Spain,Female,31,7,0.00,1,1,0,47018.75,0
63,64,15751208,Pirozzi,684,Spain,Male,56,8,78707.16,1,1,1,99398.36,0
5740,5741,15568885,Scott,620,Germany,Female,34,8,102251.57,1,1,0,120672.09,0
9624,9625,15668309,Maslow,350,France,Female,40,0,111098.85,1,1,1,172321.21,1
6191,6192,15747000,Shih,592,France,Male,27,3,0.00,2,1,1,19645.65,0

# 5. Find the shape of the dataset.
# o How many rows are there?
# o How many columns are there?

In [5]:
df.shape

(10000, 14)

In [ ]:
# 6. Display complete information about the dataset using one method.
o Number of non-null values
o Data types
o Memory usage

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

## 7. Print the names of all columns in the dataset.

In [14]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

# 8. Find the data type of every column.

In [16]:
df.select_dtypes(include=["int64"]).columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'Exited'],
      dtype='object')

In [17]:
df.select_dtypes(include=["float"]).columns

Index(['Balance', 'EstimatedSalary'], dtype='object')

In [ ]:
# 9. Check for missing values in every column using:
o isnull().sum()
o isna().sum()

In [18]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [19]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
# 10.Select only one column:
o CreditScore

In [20]:
df["CreditScore"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [ ]:
# 11.Select the following multiple columns:
o CustomerId
o Surname
o Balance
o Exited

In [21]:
df[["CustomerId","Surname","Balance","Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

# 12.Display only numeric columns using select_dtypes().

In [23]:
df.select_dtypes(include=["number"]).columns

Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

# 13.Generate the statistical summary of all numeric columns using describe().

In [24]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
# 14.Check for duplicate rows in the dataset.
o How many duplicate rows exist?

o Remove all duplicate rows.

In [25]:
df.duplicated().sum()

np.int64(0)

In [1]:
df.drop_duplicates(inplace=True)

NameError: name 'df' is not defined

In [ ]:
# 15.Count the number of customers in each class of the Exited column using
value_counts().

In [27]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [ ]:
## Operators + Loops (1-5)
1. Take two numbers from user. Perform all arithmetic operations and also check
which number is greater using comparison operators.

In [32]:
num1=int(input("enter your number:"))
num2=int(input("enter your number:"))
def check_method():
    print(num1+num2)
    print(num1-num2)
    print(num1*num2)
    print(num1/num2)
    print(num1//num2)
    print(num1%num2)

    if num1 >= num2:
        print("greater number is:",num1)
    else:
        print("greater number is:",num2)


check_method()

enter your number: 56
enter your number: 54

110
2
3024
1.037037037037037
1
2
greater number is: 56

# 2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stopcompletely when number 40 is reached using break.

In [43]:
for i in range(1,50):
    if i==40:
        break
    if i%5==0:
        continue
    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

# 3. Take numbers from user until they enter negative number. Calculate sum andaverage using while loop.

In [2]:
sum = 0
count = 0

while True:
    num = int(input("Enter a number: "))

    if num < 0:
        break

    sum += num
    count += 1

if count > 0:
    average = sum / count
    print("Sum =", sum)
    print("Average =", average)
else:
    print("No positive numbers were entered.")

Enter a number:  10
Enter a number:  54
Enter a number:  54
Enter a number:  -5

Sum = 118
Average = 39.333333333333336

In [ ]:
# 4. Print the following pattern using nested loops:
*****
****
***
**
*

In [1]:
for i in range(6, 0, -1):
    for j in range(i):
        print("*", end="")
    print()

******
*****
****
***
**
*

# 5. Find the factorial of a number using for loop and also using while loop.

In [3]:
# for loop
num = int(input("Enter a number: "))

factorial = 1

for i in range(1, num + 1):
    factorial *= i

print("Factorial =", factorial)

Enter a number:  8

Factorial = 40320

In [4]:
# while loop
num = int(input("Enter a number: "))

factorial = 1
i = 1

while i <= num:
    factorial *= i
    i += 1

print("Factorial =", factorial)

Enter a number:  6

Factorial = 720

In [ ]:
# Data Types & Methods (6-9)
6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace
spaces with -, and check if it starts with “Hello”.

In [7]:
text="hello iam learning python"

text.upper()

'HELLO IAM LEARNING PYTHON'

In [8]:
print(text.count("a"))

2

In [13]:
text.replace(" ", "-")

'hello-iam-learning-python'

In [11]:
text.startswith("hello")

True

# 7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)and reverse.

In [18]:
list1=[4,2,5,6,1,3]
list1.append(7)
print(list1)

[4, 2, 5, 6, 1, 3, 7]

In [19]:
list1.insert(8,9)
print(list1)

[4, 2, 5, 6, 1, 3, 7, 9]

In [20]:
list1.remove(9)
print(list1)

[4, 2, 5, 6, 1, 3, 7]

In [21]:
list1.pop()
print(list1)

[4, 2, 5, 6, 1, 3]

In [22]:
list1.sort(reverse=True)
print(list1)

[6, 5, 4, 3, 2, 1]

In [25]:
list1.reverse()
print(list1)

[6, 5, 4, 3, 2, 1]

In [ ]:
# 8. Create a dictionary of 4 students (name:marks). Print only those students who
scored more than 80 using items().

In [27]:
students={
    "gokul":87,
    "anand":78,
    "rabi":84,
    "akash":56,
    "mukul":52,
    
}
for name, mark in students.items():
    if mark > 80:
        print(name, mark)

gokul 87
rabi 84

## 9. Create two sets and perform union, intersection, difference. Also add and discardelements.

In [28]:
set1={1,2,3,4}
set2={4,5,6,7,8}
set1.union(set2)

{1, 2, 3, 4, 5, 6, 7, 8}

In [29]:
set1={1,2,3,4}
set2={4,5,6,7,8}
set1. intersection(set2)

{4}

In [30]:
set1={1,2,3,4}
set2={4,5,6,7,8}
set1. difference(set2)

{1, 2, 3}

In [33]:
set1={1,2,3,4}
set2={4,5,6,7,8}
set1. discard(4)
print(set1)

{1, 2, 3}

In [ ]:
OOP + Encapsulation (10-14)
10. Create a class Student with private attribute __marks. Add getter and setter with
validation (0–100).

In [36]:
class Student:
    def __init__(self,marks):
        self.__Marks=marks

    def get_marks(self):
        return self.__Marks

    def set_marks(self,new_mark):
        if  0 <=new_mark<=100:
            self.__Marks=new_mark
            print("marks are updataed",self.__Marks)
        else:
            print("mark most have 0 to 100")

st=Student(89)
print(st.get_marks())
st.set_marks(84)

89
marks are updataed 84

In [ ]:
# 11. Create class BankAccount with private __balance. Add deposit and withdraw
methods. Raise custom exception if balance becomes negative.

In [4]:
class BankAccount:
    def __init__(self,balance):
        self.__Balance=balance


    def get_balance(self):
        return self.__Balance


    def set_balance(self,amt):
        if amt >0:
            print(ant)
            

    def deposit(self,amt):
        if amt >=0:
            self.__Balance+=amt
            print("balance are deposit successfully:",self.__Balance)

        else:
            raise invalidballanceError("enter your amount more then 0")


    def withdraw(self,amt):
        if amt <= self.__Balance:
            self.__Balance-=amt
            print("withdraw amount is:",amt)
            print("amount withdraw successfully")
            print("remaining balance:",self.__Balance)


bank=BankAccount(5000)
bank.deposit(1000)
bank.withdraw(4000)

balance are deposit successfully: 6000
withdraw amount is: 4000
amount withdraw successfully
remaining balance: 2000

In [ ]:
# 12. Create class Employee with class attribute company_name. Show that it is
shared by all objects. Also update the class attribute.

In [21]:
class Employee:
    company_name="amazon"
    def __init__(self,name,dept):
        self.Name=name
        self.Departmant=dept

    def display_all_info(self):
        print("Employee 1:")
        print("Name:", self.Name)
        print("Department:", self.Departmant)
        print("Company:", Employee.company_name)

    company_name="google"
    print("company name updata")


e1 = Employee("Gokul", "Python Developer")
e1.display_all_info()
print(Employee.company_name)
print()
e2 = Employee("Rahul", "Data Analyst")
e2.display_all_info()
print()
e3=Employee("rabi","ai developer")
e3.display_all_info()

company name updata
Employee 1:
Name: Gokul
Department: Python Developer
Company: google
google

Employee 1:
Name: Rahul
Department: Data Analyst
Company: google

Employee 1:
Name: rabi
Department: ai developer
Company: google

In [ ]:
# 13. Create class Product with private __price. Add getter and setter. Setter should
not allow price less than 100.

In [25]:
class Product:
    def __init__(self,price):
        self.__Price=price

    def get_price(self):
        return self.__Price


    def set_price(self,new_price):
        if new_price >=100:
            self.__Price=new_price
            print("price update",self.__Price)
        else:
            print("price dose not allow less then 100")


p=Product(1000)
print(p.get_price())
p.set_price(50)

1000
price dose not allow less then 100

In [ ]:
## 14. Create class Rectangle with private length and width. Add method to calculate
area and perimeter.

In [29]:
class  Rectangle:
    def __init__(self,length,width):
        self.__Length=length
        self.__Width=width

    def get_length(self):
        return self.__Length

    def get_width(self):
        return self.__Width

    def set_length(self,new_length):
        if new_length >=0:
            self.__Length=new_length
            return self.__Length

        else:
            print("enter youe length more then 0")

    def set_width(self,new_width):
        if new_width >=0:
            self.__Width=new_width
            return self.__Width

        else:
            print("enter youe width more then 0")


    def calculate_area(self):
        area=self.__Length * self.__Width
        print("area of Rectangle:",area)


r=Rectangle(8,9)
print("length Rectangle:",r.set_length(7))
print("width Rectangle:",r.set_width(6))
r.calculate_area()

length Rectangle: 7
width Rectangle: 6
area of Rectangle: 42

In [ ]:
## Inheritance + Abstraction + super() (15-19)
15. Create single level inheritance: Person → Student. Use super() in constructor.

In [31]:
class Person:
    def __init__(self,name,age):
        self.Name=name
        self.Age=age

class Student(Person):
    def __init__(self,name,age,study):
        super().__init__(name,age)
        self.Study=study

    def display_info(self):
        print("student details.......")
        print("name:",self.Name)
        print("age:",self.Age)
        print("study:",self.Study)

p=Student("gokul",21,"data science")
p.display_info()

student details.......
name: gokul
age: 21
study: data science

In [ ]:
## 16. Create multi-level inheritance: Person → Employee → Manager. Override a
method at each level.

In [33]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    


class Employee(Person):
    def __init__(self, name, age, emp_id, department):
        super().__init__(name, age)
        self.emp_id = emp_id
        self.department = department

   

class Manager(Employee):
    def __init__(self, name, age, emp_id, department, team_size):
        super().__init__(name, age, emp_id, department)
        self.team_size = team_size

    def display_info(self):
        print("Manager Details:")
        print("Name:", self.name)
        print("Age:", self.age)
        print("Employee ID:", self.emp_id)
        print("Department:", self.department)
        print("Team Size:", self.team_size)



m = Manager("gokul", 35, "M201", "AI Department", 10)
m.display_info()

Manager Details:
Name: gokul
Age: 35
Employee ID: M201
Department: AI Department
Team Size: 10

In [ ]:
## 17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound()
method.

In [2]:
class Animal:
    def __init__(self, name):
        self.name = name

    def sound(self):
        print("Animal makes a sound")


class Dog(Animal):
    def sound(self):
        print(self.name, "says: Woof Woof")


class Cat(Animal):
    def sound(self):
        print(self.name, "says: Meow Meow")



dog = Dog("dogesh")
dog.sound()
print()
cat = Cat("biladon")
cat.sound()

dogesh says: Woof Woof

biladon says: Meow Meow

In [ ]:
## 18. Create abstract class Shape with abstract method area(). Implement it in Circle
and Square using super().

In [ ]:
from abc import ABC, abstractmethod
import math

#
class Shape(ABC):
    def __init__(self, value):
        self.value = value

    @abstractmethod
    def area(self):
        pass

class Circle(Shape):
    def __init__(self, radius):
        super().__init__(radius)   # Calls Shape constructo

    def area(self):
        return math.pi * self.value ** 2


# Square class
class Square(Shape):
    def __init__(self, side):
        super().__init__(side)     # Calls Shape constructor

    def area(self):
        return self.value ** 2


# Main program
c = Circle(7)
s = Square(5)

print("Area of Circle =", c.area())
print("Area of Square =", s.area())