## 1. Load the CSV file using Pandas and display the first 10 rows.

In [59]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Users\\LENOVO\\Downloads\\messy_customer_loan_dataset.csv")
df

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,CUST101131,40.0,477723.0,719.0,Self-Employed,Graduate,Single,Jaipur,mass,Home Loan,1106455.0,48,NaN,0.569,No
1531,CUST101295,65.0,1394481.0,0,Self-Employed,12th,Single,Jaipur,Mass,Personal,222828.0,120,8.0,0.344,Yes
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000,36,9.0,0.084,Yes
1533,CUST101460,45.0,543340.0,720.0,Business,Graduate,Married,Pune,Mass,Education,302389.0,72,9.0,0.089,No
1534,CUST101127,61.0,NaN,731.0,Salaried,Postgraduate,Single,Chennai,Affluent,Education,753995.0,12,5.0,0.259,No

# 2. Display the number of rows and columns in the dataset.

In [60]:
df.shape

(1535, 15)

# 3. Display all column names and identify which column names haveleading/trailing spaces.

In [61]:
df.columns
for col in df.columns:
    if col != col.strip():
        print(col)

 Customer ID
Age
credit Score
customer_segment
Monthly Visits

## 4. Clean all column names by removing extra spaces and converting them into aconsistent format such as snake_case.

In [62]:
import pandas as pd

df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\messy_customer_loan_dataset.csv")

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns
df.head()

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792.0,48,11.0,0.558,Yes
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes

# 5. Check the data type of every column.

In [63]:
df.dtypes

customer_id          object
age                  object
annual_income        object
credit_score         object
employment-type      object
education__level     object
marital_status       object
city                 object
customer_segment     object
loan_type            object
loan_amount_(inr)    object
tenure_months         int64
monthly_visits       object
debt_to_income       object
loan_approved?       object
dtype: object

## 6. Find the total number of missing values in each column.

In [64]:
df.isnull().sum()

customer_id            0
age                   71
annual_income         84
credit_score          77
employment-type       60
education__level      46
marital_status         0
city                  52
customer_segment       0
loan_type              0
loan_amount_(inr)    102
tenure_months          0
monthly_visits        55
debt_to_income        89
loan_approved?         0
dtype: int64

# 7. Find the percentage of missing values in each column.

In [65]:
df.isnull().mean() * 100

customer_id          0.000000
age                  4.625407
annual_income        5.472313
credit_score         5.016287
employment-type      3.908795
education__level     2.996743
marital_status       0.000000
city                 3.387622
customer_segment     0.000000
loan_type            0.000000
loan_amount_(inr)    6.644951
tenure_months        0.000000
monthly_visits       3.583062
debt_to_income       5.798046
loan_approved?       0.000000
dtype: float64

# 8. Find all rows where Age is missing.

In [66]:
df['age'].isnull().sum()

np.int64(71)

## 9. Find all rows where Annual Income is missing.

In [67]:
df['annual_income'].isnull().sum()

np.int64(84)

## 10.Remove completely duplicate rows and report how many duplicate rows were removed.

In [68]:
df.duplicated().sum()

np.int64(35)

In [69]:
df.drop_duplicates(inplace=True)

In [70]:
df.duplicated().sum()

np.int64(0)

# Data Type & Invalid Values
# 11.The Age column contains numbers as well as values like "unknown" and"twenty five". Clean this column and convert it into a proper numeric column.

In [71]:
df['age'] = df['age'].replace({
    "unknown": np.nan,
    "twenty five": 25
})

df['age'] = pd.to_numeric(df['age'], errors="coerce")

In [72]:
df['age'].duplicated().sum()

np.int64(1447)

## 12.The Annual Income column contains values such as 650000 INR, ₹720000,1.2L, and N/A. Clean the column and convert the valid values into numericformat.

In [73]:
df['annual_income'] = df['annual_income'].replace({
    '650000 INR': 650000,
    '₹720000': 720000,
    '1.2L': 120000,
    'N/A': np.nan
})

df['annual_income'] = pd.to_numeric(df['annual_income'], errors='coerce')

df['annual_income']

0        297809.0
1       1048283.0
2       1043481.0
3        369591.0
4        666989.0
          ...
1530     477723.0
1531    1394481.0
1532          NaN
1533     543340.0
1534          NaN
Name: annual_income, Length: 1500, dtype: float64

## 13.Clean the Credit Score column and identify values that cannot be convertedinto numbers.

In [74]:
df['credit_score'] = pd.to_numeric(df['credit_score'], errors='coerce')

In [75]:
df['credit_score']

0       698.0
1       874.0
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531      0.0
1532    686.0
1533    720.0
1534    731.0
Name: credit_score, Length: 1500, dtype: float64

## 14.The Loan Amount column contains currency symbols, text, and numericvalues. Remove the unwanted characters and convert it into numeric format.

In [76]:
df['loan_amount_(inr)']=(df['loan_amount_(inr)'].astype(str).str.replace("$","").str.replace(",","").str.replace("INR","").str.strip())
df['loan_amount_(inr)'] = pd.to_numeric(df['loan_amount_(inr)'], errors='coerce')

In [77]:
df['loan_amount_(inr)']

0         378342.0
1         751792.0
2         892792.0
3         908250.0
4         386370.0
           ...
1530     1106455.0
1531      222828.0
1532    50000000.0
1533      302389.0
1534      753995.0
Name: loan_amount_(inr), Length: 1500, dtype: float64

## 15.The Monthly Visits column contains values such as "five", "N/A", and "-".Convert valid values into numeric values and handle invalid values.

In [78]:
df['monthly_visits']=(df['monthly_visits'].astype(str).str.replace("five","5").str.replace("N/A","").str.replace("_","").str.strip())
df['monthly_visits']=pd.to_numeric(df['monthly_visits'], errors='coerce')

In [79]:
df['monthly_visits']

0        3.0
1       11.0
2        4.0
3       10.0
4        4.0
        ...
1530     NaN
1531     8.0
1532     9.0
1533     9.0
1534     5.0
Name: monthly_visits, Length: 1500, dtype: float64

## 16.Clean the Debt to Income column where some values are written like 35%and 0.4x. Convert the valid values into a consistent numeric format.

In [80]:
df['debt_to_income']=(df['debt_to_income'].astype(str).str.replace("35%","35").str.replace("0.4x","0.4").str.strip())
df['debt_to_income']=pd.to_numeric(df['debt_to_income'],errors="coerce")

In [81]:
df['debt_to_income']

0       0.258
1       0.558
2         NaN
3       0.356
4       0.169
        ...
1530    0.569
1531    0.344
1532    0.084
1533    0.089
1534    0.259
Name: debt_to_income, Length: 1500, dtype: float64

## 17.After cleaning the numerical columns, check which columns are still stored asobject data type.

In [82]:
df.select_dtypes(include='object').columns

Index(['customer_id', 'employment-type', 'education__level', 'marital_status',
       'city', 'customer_segment', 'loan_type', 'loan_approved?'],
      dtype='object')

## Categorical Cleaning
# 18.Find all unique values in the Employment-Type column.

In [83]:
df['employment-type'].unique()

array(['Self-Employed', 'Contract', 'Salaried', ' SALARIED ',
       'Self employed', 'Business', nan, 'Unknown', 'self-employed',
       'salaried'], dtype=object)

## 19.Standardize the Employment-Type column so that values such as salaried,SALARIED, and Salaried become one consistent value.

In [84]:
df['employment-type'] = df['employment-type'].str.strip().str.title()
df['employment-type']

0       Self-Employed
1            Contract
2       Self-Employed
3            Salaried
4       Self-Employed
            ...
1530    Self-Employed
1531    Self-Employed
1532         Contract
1533         Business
1534         Salaried
Name: employment-type, Length: 1500, dtype: object

## 20.Clean the Education Level column and make values such as graduate,GRADUATE, and Graduate consistent.

In [85]:
df['education__level']=df['education__level'].str.strip().str.title()
df['education__level']

0               12Th
1           Graduate
2       Postgraduate
3           Graduate
4           Graduate
            ...
1530        Graduate
1531            12Th
1532           Other
1533        Graduate
1534    Postgraduate
Name: education__level, Length: 1500, dtype: object

## 21.Clean the City column. Identify incorrect or inconsistent values such ashyderbad, Hyd, Bangalore, and Bengaluru.

In [86]:
df['city'] = df['city'].str.strip().str.title()

df['city'] = df['city'].replace({
    'Hyd': 'Hyderabad',
    'Hyderbad': 'Hyderabad',
    'Bangalore': 'Bengaluru'
})

In [87]:
df['city'].unique()

array(['Mumbai', 'Jaipur', 'Kolkata', 'Hyderabad', 'Chennai', 'Bengaluru',
       nan, 'Delhi', 'Pune'], dtype=object)

In [88]:
df['city'].value_counts(dropna=False)

city
Jaipur       195
Hyderabad    187
Mumbai       186
Bengaluru    185
Delhi        179
Chennai      178
Pune         171
Kolkata      167
NaN           52
Name: count, dtype: int64

In [89]:
df['city'].unique()

array(['Mumbai', 'Jaipur', 'Kolkata', 'Hyderabad', 'Chennai', 'Bengaluru',
       nan, 'Delhi', 'Pune'], dtype=object)

In [90]:
df.loc[df['city'].str.contains('Hyderabad', case=False, na=False), 'city'] = 'Hyderabad'

In [91]:
df['city'] = df['city'].replace({
    'MUMBAI': 'Mumbai',
    'mumbai': 'Mumbai',
    'Hyd': 'Hyderabad',
    'hyderbad': 'Hyderabad',
    'Bangalore': 'Bengaluru'
})
print(df['city'].unique())

['Mumbai' 'Jaipur' 'Kolkata' 'Hyderabad' 'Chennai' 'Bengaluru' nan 'Delhi'
 'Pune']

In [92]:
df['city'].unique()

array(['Mumbai', 'Jaipur', 'Kolkata', 'Hyderabad', 'Chennai', 'Bengaluru',
       nan, 'Delhi', 'Pune'], dtype=object)

# 22.Find all unique values in the Customer Segment column and identify invalidcategories.

In [93]:
df['customer_segment'].unique()

array(['Mass', ' PREMIUM', 'Affluent', 'Premium', 'SME', 'premium ',
       'unknown', 'High Value', 'mass'], dtype=object)

In [94]:
df['customer_segment']=df['customer_segment'].str.strip().str.title()
df['customer_segment']

0           Mass
1        Premium
2       Affluent
3        Premium
4           Mass
          ...
1530        Mass
1531        Mass
1532        Mass
1533        Mass
1534    Affluent
Name: customer_segment, Length: 1500, dtype: object

In [95]:
df['customer_segment'].unique()

array(['Mass', 'Premium', 'Affluent', 'Sme', 'Unknown', 'High Value'],
      dtype=object)

## 23.Clean the Loan Type column so that values such as personal, PERSONAL,and personal loan are standardized.

In [96]:
df['loan_type'].unique()

array(['Education', 'Auto', 'Home', 'Personal', 'Business',
       'personal loan', 'Home Loan', 'PERSONAL', 'auto ', 'Unknown'],
      dtype=object)

In [97]:
df['loan_type']=df['loan_type'].str.strip().str.title()
df['loan_type']

0       Education
1            Auto
2            Auto
3            Home
4       Education
          ...
1530    Home Loan
1531     Personal
1532     Personal
1533    Education
1534    Education
Name: loan_type, Length: 1500, dtype: object

In [98]:
df['loan_type'].unique()

array(['Education', 'Auto', 'Home', 'Personal', 'Business',
       'Personal Loan', 'Home Loan', 'Unknown'], dtype=object)

## 24.Clean the Loan Approved column where values include Yes, yes, Y, 1, No,NO, N, and 0. Convert them into only Yes/No.

In [99]:
df['loan_approved?'] = (
    df['loan_approved?']
    .str.strip()
    .str.lower()
    .replace({
        'yes': 'Yes',
        'y': 'Yes',
        '1': 'Yes',
        'no': 'No',
        'n': 'No',
        '0': 'No'
    })
)

df['loan_approved?']

0        No
1       Yes
2       Yes
3       Yes
4       Yes
       ...
1530     No
1531    Yes
1532    Yes
1533     No
1534     No
Name: loan_approved?, Length: 1500, dtype: object

## Outliers & Data Validation
## 25.Check the Age column and identify unrealistic ages such as negative ages orages above 100.

In [100]:
import pandas as pd

In [101]:
df.head()
df.shape

(1500, 15)

In [102]:
df['age'].unique

<bound method Series.unique of 0       37.0
1       36.0
2       55.0
3       54.0
4       27.0
        ...
1530    40.0
1531    65.0
1532    66.0
1533    45.0
1534    61.0
Name: age, Length: 1500, dtype: float64>

In [103]:
df['valid_age'] = (df['age'] >0) | (df['age'] < 100).isna()
df['valid_age']

0       True
1       True
2       True
3       True
4       True
        ...
1530    True
1531    True
1532    True
1533    True
1534    True
Name: valid_age, Length: 1500, dtype: bool

In [104]:
df.head()

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,valid_age
0,CUST101160,37.0,297809.0,698.0,Self-Employed,12Th,Married,Mumbai,Mass,Education,378342.0,60,3.0,0.258,No,True
1,CUST100077,36.0,1048283.0,874.0,Contract,Graduate,Single,Jaipur,Premium,Auto,751792.0,48,11.0,0.558,Yes,True
2,CUST100317,55.0,1043481.0,661.0,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792.0,84,4.0,NaN,Yes,True
3,CUST101041,54.0,369591.0,722.0,Salaried,Graduate,Single,Kolkata,Premium,Home,908250.0,84,10.0,0.356,Yes,True
4,CUST101358,27.0,666989.0,727.0,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370.0,72,4.0,0.169,Yes,True

## 26.Check the Credit Score column and identify values outside the valid credit-score range.

In [105]:
df['credit_score']

0       698.0
1       874.0
2       661.0
3       722.0
4       727.0
        ...
1530    719.0
1531      0.0
1532    686.0
1533    720.0
1534    731.0
Name: credit_score, Length: 1500, dtype: float64

In [106]:
df['credit_score'].max()

999.0

In [107]:
df['credit_score'].min()

0.0

In [108]:
df.loc[(df['credit_score'] < 300) | (df['credit_score'] > 850), 'credit_score']

1       874.0
57      852.0
83      856.0
97      905.0
113     120.0
123     999.0
178     854.0
295     250.0
296       0.0
327     856.0
342     120.0
361     858.0
369     889.0
399     863.0
542     120.0
680     120.0
690     860.0
710       0.0
726     903.0
807     120.0
830     870.0
867     872.0
923     878.0
927     250.0
930       0.0
959       0.0
964     120.0
992     867.0
1003    868.0
1068    878.0
1082      0.0
1096    865.0
1114    870.0
1132    861.0
1133    887.0
1151    863.0
1159    250.0
1217    250.0
1232    250.0
1239    876.0
1284    851.0
1286    120.0
1288      0.0
1352    250.0
1407    854.0
1461    120.0
1531      0.0
Name: credit_score, dtype: float64

## 27.Detect outliers in Annual Income using the IQR method.

In [109]:
Q1 = df['annual_income'].quantile(0.25)
Q3 = df['annual_income'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df['annual_income'] < lower) | (df['annual_income'] > upper)]

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,valid_age
14,CUST101158,60.0,1548824.0,698.0,Contract,Graduate,Married,Pune,Sme,Home,333121.0,24,10.0,0.529,No,True
61,CUST100757,55.0,1777657.0,666.0,Contract,Postgraduate,Single,Hyderabad,Premium,Education,900253.0,72,3.0,0.304,Yes,True
74,CUST100238,41.0,1907548.0,678.0,Business,Graduate,Single,Mumbai,Mass,Business,242378.0,72,0.0,NaN,Yes,True
180,CUST100421,64.0,1483255.0,751.0,Contract,Post Graduate,Married,Hyderabad,Mass,Auto,2033263.0,72,3.0,0.134,Yes,True
184,CUST100692,NaN,1895511.0,832.0,Self-Employed,Graduate,Married,Jaipur,Sme,Personal,518143.0,48,2.0,0.637,No,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1409,CUST100407,41.0,1521141.0,799.0,Self-Employed,Graduate,Single,Kolkata,Affluent,Auto,573489.0,120,2.0,0.078,Yes,True
1464,CUST101412,47.0,1996474.0,789.0,Contract,Postgraduate,Married,Kolkata,High Value,Personal,460487.0,72,4.0,0.157,Yes,True
1466,CUST100206,33.0,1604257.0,785.0,Contract,12Th,Single,Mumbai,Affluent,Business,NaN,24,3.0,0.355,No,True
1467,CUST100035,62.0,1531271.0,779.0,Business,Postgraduate,Single,Hyderabad,Mass,Personal,327941.0,24,4.0,0.179,Yes,True
1515,CUST100344,45.0,80000000.0,819.0,Self-Employed,Postgraduate,Single,Mumbai,Mass,Personal,636933.0,12,6.0,0.384,Yes,True

## 28.Detect outliers in Loan Amount using the IQR method.

In [110]:
Q1 = df['loan_amount_(inr)'].quantile(0.25)
Q3 = df['loan_amount_(inr)'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

=odf[(df['loan_amount_(inr)'] < lower) | (df['loan_amount_(inr)'] > upper)]

,customer_id,age,annual_income,credit_score,employment-type,education__level,marital_status,city,customer_segment,loan_type,loan_amount_(inr),tenure_months,monthly_visits,debt_to_income,loan_approved?,valid_age
11,CUST100679,45.0,856826.0,662.0,Self Employed,Postgraduate,Divorced,NaN,Affluent,Education,1412363.0,12,5.0,0.487,Yes,True
25,CUST100071,58.0,454340.0,743.0,Business,Graduate,Single,Jaipur,Premium,Business,1545154.0,72,3.0,0.333,Yes,True
58,CUST100345,63.0,477076.0,785.0,Salaried,Graduate,MARRIED,Chennai,Sme,Education,1575763.0,24,8.0,0.419,No,True
157,CUST101362,24.0,782709.0,842.0,Salaried,12Th,Married,NaN,Premium,Personal,120000000.0,48,6.0,NaN,No,True
180,CUST100421,64.0,1483255.0,751.0,Contract,Post Graduate,Married,Hyderabad,Mass,Auto,2033263.0,72,3.0,0.134,Yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392,CUST101039,41.0,396322.0,661.0,Self-Employed,Postgraduate,Single,Kolkata,Affluent,Education,1550762.0,84,4.0,0.337,No,True
1439,CUST100764,64.0,761542.0,731.0,NaN,Graduate,MARRIED,Bengaluru,Mass,Auto,2170814.0,72,2.0,0.247,Yes,True
1469,CUST100509,33.0,850268.0,829.0,Business,NaN,Married,Kolkata,Mass,Personal,1647932.0,72,4.0,0.329,Yes,True
1501,CUST100475,50.0,NaN,802.0,Contract,12Th,Divorced,Kolkata,Mass,Personal,1488587.0,36,5.0,0.023,Yes,True
1532,CUST100861,66.0,NaN,686.0,Contract,Other,Married,Delhi,Mass,Personal,50000000.0,36,9.0,0.084,Yes,True

## 29.Check the Debt to Income column and identify impossible values such asnegative values or values greater than 1.

In [111]:
df['debt_to_income']=(df['debt_to_income']<0) | (df['debt_to_income'] > 0)
df['debt_to_income']

0        True
1        True
2       False
3        True
4        True
        ...
1530     True
1531     True
1532     True
1533     True
1534     True
Name: debt_to_income, Length: 1500, dtype: bool

In [114]:
df.to_csv("clean_data1.csv")