## 1. Column Names
# Display all column names. Identify columns having leading/trailing spaces and
# rename all columns into a consistent snake_case format.

In [2]:
import pandas as pd
df=pd.read_csv("C:\\Users\\LENOVO\\Downloads\\matplotlib_messy_sales_2000.csv")
df.head(2)

,Customer ID,Order Date,City,Product Category,Customer Segment,Gender,Sales Channel,Age,Units Sold,Unit Price,Discount %,Customer Rating,Is Active,Returned,Payment Method,Gross Sales,Discount Amount,Revenue,Cost,Profit
0,CUST00594,2025-05-05 00:00:00,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14
1,CUST01103,2025-10-22 00:00:00,Mumbai,Clothing,Premium,Female,Corporate,38.0,5,16789.55,10.59,4.3,1,0,Cash,83947.75,8890.07,75057.68,61426.31,13631.37

In [3]:
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_",regex=True)
df.columns

Index(['customer_id', 'order_date', 'city', 'product_category',
       'customer_segment', 'gender', 'sales_channel', 'age', 'units_sold',
       'unit_price', 'discount_%', 'customer_rating', 'is_active', 'returned',
       'payment_method', 'gross_sales', 'discount_amount', 'revenue', 'cost',
       'profit'],
      dtype='object')

In [4]:
df

,customer_id,order_date,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05 00:00:00,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14
1,CUST01103,2025-10-22 00:00:00,Mumbai,Clothing,Premium,Female,Corporate,38.0,5,16789.55,10.59,4.3,1,0,Cash,83947.75,8890.07,75057.68,61426.31,13631.37
2,CUST00690,2025-04-24 00:00:00,Delhi,Home & Kitchen,Regular,Male,Retail,65.0,2,24579.97,36.22,4.5,1,0,Debit Card,49159.94,17805.73,31354.21,24948.21,6406.00
3,CUST00215,2025-05-17 00:00:00,Chennai,Electronics,Regular,Male,Corporate,34.0,9,6240.13,20.44,3.9,1,0,Net Banking,56161.17,11479.34,NaN,26470.33,18211.50
4,CUST01270,2025-08-30 00:00:00,Delhi,Clothing,Budget,Female,Corporate,41.0,1,23491.23,10.48,3.7,1,0,Net Banking,23491.23,2461.88,21029.35,12312.38,8716.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CUST00043,2025-12-17 00:00:00,Pune,Sports,Premium,Male,Retail,24.0,10,9181.27,18.05,3.7,1,0,UPI,91812.70,16572.19,75240.51,39994.75,35245.76
2016,CUST00602,2025-12-22 00:00:00,Pune,Sports,Regular,Female,Retail,44.0,9,6947.94,32.93,1.5,1,0,Cash,62531.46,20591.61,41939.85,33246.33,8693.52
2017,CUST01708,2025-05-28 00:00:00,Hyderabad,Home & Kitchen,Premium,Male,Retail,56.0,5,5393.37,25.19,3.4,1,0,UPI,26966.85,6792.95,20173.90,13654.93,6518.97
2018,CUST00614,2025-08-27 00:00:00,Chennai,Sports,Premium,Male,Online,41.0,7,10803.59,0.5,5.0,1,0,UPI,75625.13,378.13,75247.00,46822.20,28424.80
2019,CUST01948,2025-12-23 00:00:00,Pune,Beauty,Regular,Female,Retail,68.0,12,18336.56,23.29,4.7,1,0,Credit Card,220038.72,51247.02,168791.70,107140.44,61651.26

## 2. Duplicate Records
## Find the number of duplicate rows. Remove the duplicate records and verify that noduplicates remain.

In [5]:
df.duplicated().sum()

np.int64(20)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.duplicated().sum()

np.int64(0)

## 3. Missing Values
## Display the missing-value count and missing-value percentage for every column.

In [8]:
df.isnull().sum()

customer_id          0
order_date           4
city                25
product_category    24
customer_segment     0
gender               0
sales_channel        0
age                 27
units_sold           4
unit_price          24
discount_%          28
customer_rating     25
is_active            0
returned             0
payment_method      25
gross_sales          0
discount_amount      0
revenue             25
cost                 0
profit               0
dtype: int64

In [9]:
calculate_percentage=df.isnull().sum() / len(df) * 100
calculate_percentage

customer_id         0.00
order_date          0.20
city                1.25
product_category    1.20
customer_segment    0.00
gender              0.00
sales_channel       0.00
age                 1.35
units_sold          0.20
unit_price          1.20
discount_%          1.40
customer_rating     1.25
is_active           0.00
returned            0.00
payment_method      1.25
gross_sales         0.00
discount_amount     0.00
revenue             1.25
cost                0.00
profit              0.00
dtype: float64

## 4. Missing Categorical Values
# Handle missing values in city, product_category, and payment_method using an
# appropriate strategy.

In [10]:
df[['city','product_category','payment_method']].isnull().sum()

city                25
product_category    24
payment_method      25
dtype: int64

In [11]:
mode = df[['city', 'product_category', 'payment_method']].mode().iloc[0]
mode

city                  Bengaluru
product_category       Clothing
payment_method      Credit Card
Name: 0, dtype: object

In [12]:
df[['city','product_category','payment_method']]=df[['city','product_category','payment_method']].fillna(mode)
df[['city','product_category','payment_method']]

           city product_category payment_method
0        Mumbai         Clothing            UPI
1        Mumbai         Clothing           Cash
2         Delhi   Home & Kitchen     Debit Card
3       Chennai      Electronics    Net Banking
4         Delhi         Clothing    Net Banking
...         ...              ...            ...
2015       Pune           Sports            UPI
2016       Pune           Sports           Cash
2017  Hyderabad   Home & Kitchen            UPI
2018    Chennai           Sports            UPI
2019       Pune           Beauty    Credit Card

[2000 rows x 3 columns]

In [13]:
df[['city','product_category','payment_method']].isnull().sum()

city                0
product_category    0
payment_method      0
dtype: int64

## 5. Missing Numerical Values
## Handle missing values in age, unit_price, discount_pct, customer_rating, and
## revenue. Explain why you selected mean, median, or another method.

In [14]:
df.head(1)

,customer_id,order_date,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05 00:00:00,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14

In [15]:
df[['age','unit_price','discount_%','customer_rating']].isnull().sum()

age                27
unit_price         24
discount_%         28
customer_rating    25
dtype: int64

In [16]:
df[['age','unit_price','discount_%','customer_rating']].dtypes

age                 object
unit_price          object
discount_%          object
customer_rating    float64
dtype: object

In [17]:
df[['age','unit_price','discount_%','customer_rating']] = df[['age','unit_price','discount_%','customer_rating']].apply(pd.to_numeric, errors='coerce')
df[['age','unit_price','discount_%','customer_rating']]

       age  unit_price  discount_%  customer_rating
0     36.0    24235.73       22.91              1.9
1     38.0    16789.55       10.59              4.3
2     65.0    24579.97       36.22              4.5
3     34.0     6240.13       20.44              3.9
4     41.0    23491.23       10.48              3.7
...    ...         ...         ...              ...
2015  24.0     9181.27       18.05              3.7
2016  44.0     6947.94       32.93              1.5
2017  56.0     5393.37       25.19              3.4
2018  41.0    10803.59        0.50              5.0
2019  68.0    18336.56       23.29              4.7

[2000 rows x 4 columns]

In [18]:
mean=df[['age','unit_price','discount_%','customer_rating']].mean()
mean

age                   44.046130
unit_price         16330.343538
discount_%            20.897913
customer_rating        3.012709
dtype: float64

In [19]:
df[['age','unit_price','discount_%','customer_rating']]=df[['age','unit_price','discount_%','customer_rating']].fillna(mean)
df[['age','unit_price','discount_%','customer_rating']]

       age  unit_price  discount_%  customer_rating
0     36.0    24235.73       22.91              1.9
1     38.0    16789.55       10.59              4.3
2     65.0    24579.97       36.22              4.5
3     34.0     6240.13       20.44              3.9
4     41.0    23491.23       10.48              3.7
...    ...         ...         ...              ...
2015  24.0     9181.27       18.05              3.7
2016  44.0     6947.94       32.93              1.5
2017  56.0     5393.37       25.19              3.4
2018  41.0    10803.59        0.50              5.0
2019  68.0    18336.56       23.29              4.7

[2000 rows x 4 columns]

In [20]:
df[['age','unit_price','discount_%','customer_rating']].isnull().sum()

age                0
unit_price         0
discount_%         0
customer_rating    0
dtype: int64

## 6. Date Cleaning
## Convert order_date into a proper datetime format. Identify invalid date values and
## handle them appropriately.

In [21]:
df['order_date']=pd.to_datetime(df['order_date'],errors="coerce")
df['order_date']

0      2025-05-05
1      2025-10-22
2      2025-04-24
3      2025-05-17
4      2025-08-30
          ...
2015   2025-12-17
2016   2025-12-22
2017   2025-05-28
2018   2025-08-27
2019   2025-12-23
Name: order_date, Length: 2000, dtype: datetime64[ns]

In [22]:
df['order_date'].isnull().sum()

np.int64(25)

In [23]:
df=df.dropna(subset=['order_date'])

In [24]:
df['order_date'].isnull().sum()

np.int64(0)

## 7. Age Cleaning
# The age column contains values such as 25 years, 30 yrs, 45Y, and N/A. Extract thenumerical age and convert the column into a numeric datatype.

In [25]:
df['age']=pd.to_numeric(df['age'],errors="coerce")
df['age']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\1234452591.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age']=pd.to_numeric(df['age'],errors="coerce")

0       36.0
1       38.0
2       65.0
3       34.0
4       41.0
        ...
2015    24.0
2016    44.0
2017    56.0
2018    41.0
2019    68.0
Name: age, Length: 1975, dtype: float64

In [26]:
df['age'].dtypes

dtype('float64')

## 8. Age Outliers
# Identify unrealistic ages such as 120, 150, and 200. Detect them using the IQRmethod and handle them appropriately.

In [27]:
df['age']>=100

0       False
1       False
2       False
3       False
4       False
        ...
2015    False
2016    False
2017    False
2018    False
2019    False
Name: age, Length: 1975, dtype: bool

In [28]:
Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['age'] < lower) | (df['age'] > upper)]

outliers

,customer_id,order_date,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
193,CUST01152,2025-08-17,Hyderabad,Electronics,Premium,Female,Corporate,150.0,10,7888.62,2.94,1.8,1,1,Net Banking,78886.20,2319.25,76566.95,61088.36,15478.59
256,CUST01689,2025-03-26,Mumbai,Clothing,Budget,Male,Corporate,120.0,2,23011.77,35.61,3.5,1,0,Net Banking,46023.54,16388.98,29634.56,21762.78,7871.78
323,CUST00564,2025-05-01,Mumbai,Clothing,Budget,Female,Retail,120.0,13,5388.98,36.86,4.1,1,0,Credit Card,70056.74,25822.91,44233.83,22681.23,21552.60
467,CUST01798,2025-01-23,Mumbai,Beauty,Regular,Male,Online,120.0,14,11747.60,3.50,3.6,0,0,Credit Card,164466.40,5756.32,158710.08,101891.62,56818.46
534,CUST01658,2025-03-29,Pune,Home & Kitchen,Regular,Male,Corporate,200.0,3,22272.83,24.35,1.5,0,0,Debit Card,66818.49,16270.30,50548.19,40449.06,10099.13
647,CUST00838,2025-10-26,Chennai,Electronics,Budget,Female,Retail,120.0,9,13318.51,22.99,3.4,0,0,UPI,119866.59,27557.33,92309.26,58284.17,34025.09
777,CUST01245,2025-04-17,Mumbai,Beauty,Premium,Female,Online,150.0,14,10252.23,9.41,4.5,1,1,Credit Card,143531.22,13506.29,130024.93,77393.39,52631.54
869,CUST01120,2025-10-22,Delhi,Beauty,Budget,Male,Retail,150.0,9,19580.66,17.37,4.1,1,0,UPI,176225.94,30610.45,145615.49,76225.06,69390.43
991,CUST01989,2025-09-08,Mumbai,Electronics,Regular,Male,Corporate,150.0,6,2945.85,11.78,3.5,0,0,Credit Card,17675.10,2082.13,15592.97,10349.59,5243.38
1023,CUST01998,2025-08-15,Mumbai,Sports,Regular,Male,Online,120.0,12,14713.78,39.96,4.9,1,0,Net Banking,176565.36,70555.52,106009.84,70652.27,35357.57
1532,CUST00886,2025-02-09,Mumbai,Sports,Premium,Female,Retail,150.0,6,5779.57,33.86,1.6,1,0,Cash,34677.42,11741.77,22935.65,17631.99,5303.66
1731,CUST00783,2025-05-24,Delhi,Electronics,Budget,Female,Corporate,120.0,9,11462.24,34.44,1.4,0,0,Debit Card,103160.16,35528.36,67631.80,40478.53,27153.27
2000,CUST01513,2025-09-07,Pune,Clothing,Regular,Male,Corporate,120.0,11,20446.77,30.73,2.8,1,0,Credit Card,224914.47,69116.22,155798.25,83293.18,72505.07

In [29]:
median_age = df['age'].median()
median_age

44.0

In [30]:
df['age'].fillna(median_age)

0       36.0
1       38.0
2       65.0
3       34.0
4       41.0
        ...
2015    24.0
2016    44.0
2017    56.0
2018    41.0
2019    68.0
Name: age, Length: 1975, dtype: float64

## 9. Unit Price Cleaning
## The unit_price column contains values such as ₹15000, $20000, 25000 INR, and 10k.Convert all valid values into a single numeric format.

In [31]:
df['unit_price']=df['unit_price'].astype(str).str.replace("₹","").str.replace("$","").str.replace("INR","").str.replace("k","")
df['unit_price']=pd.to_numeric(df['unit_price'],errors="coerce")
df['unit_price']
df['unit_price']=df['unit_price'].astype('float')
df['unit_price']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\3362737167.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['unit_price']=df['unit_price'].astype(str).str.replace("₹","").str.replace("$","").str.replace("INR","").str.replace("k","")
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\3362737167.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['unit_price']=pd.to_numeric(df['unit_price'],errors="coerce")
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\3362737167.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['unit_price']=df['unit_price'].astype('float')

0       24235.73
1       16789.55
2       24579.97
3        6240.13
4       23491.23
          ...
2015     9181.27
2016     6947.94
2017     5393.37
2018    10803.59
2019    18336.56
Name: unit_price, Length: 1975, dtype: float64

## 10. Unit Price Outliers
# Detect extreme unit_price values using the IQR method. Compare the number ofoutliers before and after treatment.

In [32]:
Q1 = df['unit_price'].quantile(0.25)
Q3 = df['unit_price'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers_before = ((df['unit_price'] < lower) | 
                   (df['unit_price'] > upper)).sum()

median_price = df['unit_price'].median()
df.loc[(df['unit_price'] < lower) | 
       (df['unit_price'] > upper), 'unit_price'] = median_price

outliers_after = ((df['unit_price'] < lower) | 
                  (df['unit_price'] > upper)).sum()

print("Outliers before:", outliers_before)
print("Outliers after:", outliers_after)

Outliers before: 14
Outliers after: 0

## 11. Units Sold Cleaning
# Clean values such as 5 units, 10 pcs, twenty, N/A, and 3 and convert the column intoa numeric datatype.

In [33]:
df.head(1)

,customer_id,order_date,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05,Mumbai,Clothing,premium,Male,Retail,36.0,8,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14

In [42]:
df['units_sold'] = df['units_sold'].astype(str).str.replace("units","").str.replace("pcs","").str.replace("twenty","20").str.replace("N/A","").str.strip()
df['units_sold'] = pd.to_numeric(df['units_sold'], errors="coerce")
df['units_sold']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\4088366579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['units_sold'] = df['units_sold'].astype(str).str.replace("units","").str.replace("pcs","").str.replace("twenty","20").str.replace("N/A","").str.strip()
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\4088366579.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['units_sold'] = pd.to_numeric(df['units_sold'], errors="coerce")

0        8.0
1        5.0
2        2.0
3        9.0
4        1.0
        ...
2015    10.0
2016     9.0
2017     5.0
2018     7.0
2019    12.0
Name: units_sold, Length: 1975, dtype: float64

## 12. Discount Cleaning
## Clean values such as 10%, 20 percent, 5 %, none, and N/A. Convert the finaldiscount_pct column into numeric values between 0 and 100.

In [43]:
df.head(1)

,customer_id,order_date,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05,Mumbai,Clothing,premium,Male,Retail,36.0,8.0,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14

In [47]:
df['discount_%'] = (
    df['discount_%']
    .astype(str)
    .str.replace('%', '',)
    .str.replace('percent', '',)
    .str.replace('none', '',)
    .str.replace('N/A', '', )
    .str.strip()
)

df['discount_%'] = pd.to_numeric(df['discount_%'],errors='coerce')

df['discount_%']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\3025524689.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['discount_%'] = (
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\3025524689.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['discount_%'] = pd.to_numeric(df['discount_%'],errors='coerce')

0       22.91
1       10.59
2       36.22
3       20.44
4       10.48
        ...
2015    18.05
2016    32.93
2017    25.19
2018     0.50
2019    23.29
Name: discount_%, Length: 1975, dtype: float64

## 13. Discount Outliers
# Identify invalid discount values such as 75, 90, and 120. Determine which values areunrealistic and handle them.

In [48]:
invalid_discounts = df[
    (df['discount_%'] < 0) | (df['discount_%'] > 100)
]

print(invalid_discounts[['discount_%']])

      discount_%
92         120.0
567        120.0
884        120.0
1419       120.0
1994       120.0

In [51]:
import numpy as np
df.loc[
    (df['discount_%'] < 0) | (df['discount_%'] > 100),
    'discount_%'
] = np.nan

In [52]:
print(df['discount_%'])

0       22.91
1       10.59
2       36.22
3       20.44
4       10.48
        ...
2015    18.05
2016    32.93
2017    25.19
2018     0.50
2019    23.29
Name: discount_%, Length: 1975, dtype: float64

In [ ]:
## 14. City Standardization
Standardize inconsistent city values such as:
o Mumbai
o mumbai
o MUMBAI
o Mumbai
o Bangalore
o bangalore
o Hyderbad

In [54]:
df['city']=df['city'].str.strip().str.title()
df['city'].str.replace("Bangalore","Bengaluru").str.replace("Hyderbad","Hyderabad")

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\1225249893.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city']=df['city'].str.strip().str.title()

0          Mumbai
1          Mumbai
2           Delhi
3         Chennai
4           Delhi
          ...
2015         Pune
2016         Pune
2017    Hyderabad
2018      Chennai
2019         Pune
Name: city, Length: 1975, dtype: object

## 15. Product Category Cleaning
# Standardize values such as Electronics, electronics, ELECTRONICS, Home and Kitchen,home & kitchen, and Beauty .

In [55]:
df['product_category']=df['product_category'].str.title()
df['product_category']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\3372976063.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['product_category']=df['product_category'].str.title()

0             Clothing
1             Clothing
2       Home & Kitchen
3          Electronics
4             Clothing
             ...
2015            Sports
2016            Sports
2017    Home & Kitchen
2018            Sports
2019            Beauty
Name: product_category, Length: 1975, dtype: object

## 16. Gender Cleaning
# Standardize values such as Male, male, Male, FEMALE, female , M, and F intoconsistent categories.

In [56]:
df['gender']=df['gender'].str.title()
df['gender']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\3058956597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender']=df['gender'].str.title()

0         Male
1       Female
2         Male
3         Male
4       Female
         ...
2015      Male
2016    Female
2017      Male
2018      Male
2019    Female
Name: gender, Length: 1975, dtype: object

## 17. Customer Segment Cleaning
# Identify invalid values such as Prem, Reg, VIP, and Unknown. Map valid variations tothe correct categories and decide how to handle invalid categories.

In [57]:
df.head(1)

,customer_id,order_date,city,product_category,customer_segment,gender,sales_channel,age,units_sold,unit_price,discount_%,customer_rating,is_active,returned,payment_method,gross_sales,discount_amount,revenue,cost,profit
0,CUST00594,2025-05-05,Mumbai,Clothing,premium,Male,Retail,36.0,8.0,24235.73,22.91,1.9,1,0,UPI,193885.84,44419.25,149466.59,88698.45,60768.14

In [61]:
df['customer_segment'].unique()

array(['premium', 'Premium', 'Regular', 'Budget', 'Reg', 'Prem'],
      dtype=object)

In [63]:
df['customer_segment'] = df['customer_segment'].str.strip().str.lower()

df['customer_segment'] = df['customer_segment'].replace({
    'prem': 'Premium',
    'reg': 'Regular',
    'vip': 'VIP',
    'unknown': None
})

df['customer_segment']

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\484249890.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_segment'] = df['customer_segment'].str.strip().str.lower()
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\484249890.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_segment'] = df['customer_segment'].replace({

0       premium
1       premium
2       regular
3       regular
4        budget
         ...
2015    premium
2016    regular
2017    premium
2018    premium
2019    regular
Name: customer_segment, Length: 1975, dtype: object

In [ ]:
## 18. Binary Column Cleaning
Clean is_active and returned, where values contain combinations of:
o 0/1
o Yes/No
o Y/N
o Active/Inactive
o Returned/Not Returned

Sumit Sir Notes
Convert both columns into a consistent 0/1 binary format.

In [64]:

df['is_active'] = df['is_active'].replace({
    'Yes': 1,
    'Y': 1,
    'Active': 1,
    'No': 0,
    'N': 0,
    'Inactive': 0
})

# Clean returned
df['returned'] = df['returned'].replace({
    'Yes': 1,
    'Y': 1,
    'Returned': 1,
    'No': 0,
    'N': 0,
    'Not Returned': 0
})

df[['is_active', 'returned']]

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\1008533967.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_active'] = df['is_active'].replace({
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10036\1008533967.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['returned'] = df['returned'].replace({

     is_active returned
0            1        0
1            1        0
2            1        0
3            1        0
4            1        0
...        ...      ...
2015         1        0
2016         1        0
2017         1        0
2018         1        0
2019         1        0

[1975 rows x 2 columns]

In [ ]:
## 19. Data-Type Validation
After cleaning, display df.info() and verify that:
o Dates are datetime
o Numerical columns are numeric
o Binary columns contain only 0 and 1
o Categorical columns contain clean strings

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1975 entries, 0 to 2019
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1975 non-null   object
 1   order_date        1975 non-null   datetime64[ns]
 2   city              1975 non-null   object
 3   product_category  1975 non-null   object
 4   customer_segment  1975 non-null   object
 5   gender            1975 non-null   object
 6   sales_channel     1975 non-null   object
 7   age               1975 non-null   float64
 8   units_sold        1971 non-null   float64
 9   unit_price        1975 non-null   float64
 10  discount_%        1970 non-null   float64
 11  customer_rating   1975 non-null   float64
 12  is_active         1975 non-null   object
 13  returned          1975 non-null   object
 14  payment_method    1975 non-null   object
 15  gross_sales       1975 non-null   float64
 16  discount_amount   1975 non-null   float64
 17  revenue           1950 non-null   float64
 18  cost              1975 non-null   float64
 19  profit            1975 non-null   float64
dtypes: datetime64[ns](1), float64(10), object(9)
memory usage: 324.0+ KB

In [ ]:
## 20. Final Data Quality Check — Hardest
Perform a complete final audit of the cleaned dataset:
o Check duplicate rows
o Check missing values
o Check invalid dates
o Check numerical columns
o Check outliers
o Check categorical inconsistencies
o Check binary values
o Check datatypes
o Verify that Revenue, Cost, and Profit are logically consistent

In [67]:
df.duplicated().sum()

np.int64(0)

In [68]:
df.isnull().sum()

customer_id          0
order_date           0
city                 0
product_category     0
customer_segment     0
gender               0
sales_channel        0
age                  0
units_sold           4
unit_price           0
discount_%           5
customer_rating      0
is_active            0
returned             0
payment_method       0
gross_sales          0
discount_amount      0
revenue             25
cost                 0
profit               0
dtype: int64

In [69]:
df.to_csv("cleaned_data_matplotlib_messy_sales.csv", index=False)